spring:
   jpa:
     properties:
         hibernate:
            jdbc:
                lob:
                   non_contextual_creation: true
            show_sql: true
            format_sql: true
            ddl-auto: update
     generate-ddl: true
              
   datasource:
        url: ${DATABASE_URL}
        
